In [2]:
import numpy as np

In [38]:
array1 = np.arange(10,200,2)
array2 = np.arange(-1,30,0.5)


In [42]:
cat_array = np.concatenate((array1,array2))
print(cat_array)

[  10.    12.    14.    16.    18.    20.    22.    24.    26.    28.    30.
   32.    34.    36.    38.    40.    42.    44.    46.    48.    50.    52.
   54.    56.    58.    60.    62.    64.    66.    68.    70.    72.    74.
   76.    78.    80.    82.    84.    86.    88.    90.    92.    94.    96.
   98.   100.   102.   104.   106.   108.   110.   112.   114.   116.   118.
  120.   122.   124.   126.   128.   130.   132.   134.   136.   138.   140.
  142.   144.   146.   148.   150.   152.   154.   156.   158.   160.   162.
  164.   166.   168.   170.   172.   174.   176.   178.   180.   182.   184.
  186.   188.   190.   192.   194.   196.   198.    -1.    -0.5    0.
    0.5    1.     1.5    2.     2.5    3.     3.5    4.     4.5    5.
    5.5    6.     6.5    7.     7.5    8.     8.5    9.     9.5   10.
   10.5   11.    11.5   12.    12.5   13.    13.5   14.    14.5   15.
   15.5   16.    16.5   17.    17.5   18.    18.5   19.    19.5   20.
   20.5   21.    21.5   22.    22.

In [23]:
array1 ** 2

array([100, 144, 196, 256, 324])

In [32]:
np.linspace(0,200,1234) # for linear spacing between two endpoints

array([  0.00000000e+00,   1.62206002e-01,   3.24412003e-01, ...,
         1.99675588e+02,   1.99837794e+02,   2.00000000e+02])

In [33]:
np.logspace(0, 3, 5)

array([    1.        ,     5.62341325,    31.6227766 ,   177.827941  ,
        1000.        ])

In [41]:
cat_array[cat_array < 50]

array([ 10. ,  12. ,  14. ,  16. ,  18. ,  20. ,  22. ,  24. ,  26. ,
        28. ,  30. ,  32. ,  34. ,  36. ,  38. ,  40. ,  42. ,  44. ,
        46. ,  48. ,  -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,
         2.5,   3. ,   3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,
         7. ,   7.5,   8. ,   8.5,   9. ,   9.5,  10. ,  10.5,  11. ,
        11.5,  12. ,  12.5,  13. ,  13.5,  14. ,  14.5,  15. ,  15.5,
        16. ,  16.5,  17. ,  17.5,  18. ,  18.5,  19. ,  19.5,  20. ,
        20.5,  21. ,  21.5,  22. ,  22.5,  23. ,  23.5,  24. ,  24.5,
        25. ,  25.5,  26. ,  26.5,  27. ,  27.5,  28. ,  28.5,  29. ,  29.5])

In [45]:
np.where(cat_array < 50) [0]

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156])

In [47]:
array3 = array1 / 2

In [49]:
array3 + array1

array([  15.,   18.,   21.,   24.,   27.,   30.,   33.,   36.,   39.,
         42.,   45.,   48.,   51.,   54.,   57.,   60.,   63.,   66.,
         69.,   72.,   75.,   78.,   81.,   84.,   87.,   90.,   93.,
         96.,   99.,  102.,  105.,  108.,  111.,  114.,  117.,  120.,
        123.,  126.,  129.,  132.,  135.,  138.,  141.,  144.,  147.,
        150.,  153.,  156.,  159.,  162.,  165.,  168.,  171.,  174.,
        177.,  180.,  183.,  186.,  189.,  192.,  195.,  198.,  201.,
        204.,  207.,  210.,  213.,  216.,  219.,  222.,  225.,  228.,
        231.,  234.,  237.,  240.,  243.,  246.,  249.,  252.,  255.,
        258.,  261.,  264.,  267.,  270.,  273.,  276.,  279.,  282.,
        285.,  288.,  291.,  294.,  297.])

In [50]:
randarray = np.random.randint(0,100, 20)

In [51]:
randarray

array([76, 77,  3,  0, 63, 16, 78, 94, 86, 67, 60, 72, 60, 90, 24, 97, 85,
       99, 86, 48])

In [53]:
print(randarray.max())
print(randarray.min())
print(randarray.mean())
print(randarray.sum())

99
0
64.05
1281


In [56]:
print(randarray.cumsum())

[  76  153  156  156  219  235  313  407  493  560  620  692  752  842  866
  963 1048 1147 1233 1281]


In [63]:
np.argmin(randarray)

3

In [58]:
randarray.argmin()

3

In [64]:
np.zeros(100)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [65]:
np.ones((5,20))

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
         1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [67]:
import os
os.listdir("./data")

['Uber-Jan-Feb-FOIL.csv']

In [83]:
uber_data = np.genfromtxt("./data/Uber-Jan-Feb-FOIL.csv", delimiter=",", unpack=True, dtype=str, skip_header=True)

In [86]:
dates = uber_data[1]
trips = uber_data[3]

In [91]:
trips[dates == '1/1/2015'].astype(int).std()

9457.8792622283399